.Dd August 15, 2020
.Dt tuf-tray 1 SMM
.Os TUF Manager
.Sh NAME
.Nm tuf-tray
.Nd Manage the TUF Gaming notebook
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
This program should be started automatically by the desktop environment. It is a tray icon that runs in the status bar and allows changing fan speeds, opening the TUF Manager GUI, and notifications about fan speed changes.
.Sh SEE ALSO
.Xr tuf-cli 1 ,
.Xr tuf-gui 1
.Sh AUTHORS
.An Chris Cromer <chris@cromer.cl>
