.Dd August 15, 2020
.Dt tuf-gui 1 SMM
.Os TUF Manager
.Sh NAME
.Nm tuf-gui
.Nd Manage the TUF Gaming notebook
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
This program allows controlling the fan modes and keyboard lighting of Asus TUF Gaming notebooks via a GUI.
There are 2 available configuration options. Restore settings which will allow settings to be restored when TUF Manager is run either from CLI, GUI, or the Tray Icon. The other setting is notifications, which if set will notify the user via tray icon that the fan mode changed.
.Sh SEE ALSO
.Xr tuf-cli 1 ,
.Xr tuf-tray 1
.Sh AUTHORS
.An Chris Cromer <chris@cromer.cl>
